// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/credits/:userId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/credits/[userId].get').default>>>>
    }
    '/api/credits/boost': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/credits/boost.post').default>>>>
    }
    '/api/listings/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/listings/[id].get').default>>>>
    }
    '/api/listings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/listings/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/listings/index.post').default>>>>
    }
    '/api/sellers/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sellers/[id].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}