// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/alerts/:sellerId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/alerts/[sellerId].get').default>>>>
    }
    '/api/alerts/toggle': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/alerts/toggle.post').default>>>>
    }
    '/api/auth/forgot-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/forgot-password.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/auth/resend-verification': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/resend-verification.post').default>>>>
    }
    '/api/auth/reset-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/reset-password.post').default>>>>
    }
    '/api/auth/verify-email': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/verify-email.post').default>>>>
    }
    '/api/credits/boost': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/credits/boost.post').default>>>>
    }
    '/api/credits/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/credits/me.get').default>>>>
    }
    '/api/favorites/:userId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/favorites/[userId].get').default>>>>
    }
    '/api/favorites/toggle': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/favorites/toggle.post').default>>>>
    }
    '/api/listings/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/listings/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/listings/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/listings/[id].patch').default>>>>
    }
    '/api/listings/:id/sold': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/listings/[id]/sold.post').default>>>>
    }
    '/api/listings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/listings/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/listings/index.post').default>>>>
    }
    '/api/notifications': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/index.get').default>>>>
    }
    '/api/notifications/read': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/read.post').default>>>>
    }
    '/api/sellers/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sellers/[id].get').default>>>>
    }
    '/api/sellers/me': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sellers/me.patch').default>>>>
    }
    '/api/sellers/me/listings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sellers/me/listings.get').default>>>>
    }
    '/auth/facebook': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/auth/facebook.get').default>>>>
    }
    '/auth/google': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/auth/google.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/api/_auth/session': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.get').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}